### ISSUE TITLE
Format of elapsed time makes no sense over 1mn. 

### ISSUE THREAD

**Issue by fulmicoton** [PSeitz/rust_measure_time#2]
Over 1mn the debug looks like this
```
blabla took 1.85m
```
I would have preferred `1mn51s` or something.

Also before 1s:
```
186.597234ms
```
Which might be a little bit too precise.

**Comment by PSeitz** [comment]
Fixed with measure_time v0.8.0, more details about the updated behavior in https://github.com/PSeitz/rust_measure_time/commit/bd829342aaed87db84f49ee6f7f46749b8c8e2ca
